// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhvCNi_QA0Durp_4gI2AsQ84d5dij96M',
    appId: '1:765882164627:android:9b8a6e1d97b3449f5af466',
    messagingSenderId: '765882164627',
    projectId: 'app-convention',
    storageBucket: 'app-convention.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiCqbzWk_4EdtEaB9jC8RGARluh-Ws-WU',
    appId: '1:765882164627:ios:bf4fa9a177f5dd1d5af466',
    messagingSenderId: '765882164627',
    projectId: 'app-convention',
    storageBucket: 'app-convention.firebasestorage.app',
    iosBundleId: 'com.example.appConvention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiCqbzWk_4EdtEaB9jC8RGARluh-Ws-WU',
    appId: '1:765882164627:ios:bf4fa9a177f5dd1d5af466',
    messagingSenderId: '765882164627',
    projectId: 'app-convention',
    storageBucket: 'app-convention.firebasestorage.app',
    iosBundleId: 'com.example.appConvention',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5SbidwS9Bfw5FFZnOwzLrwBGOs-_qh8',
    appId: '1:765882164627:web:9c280ebe0c8159cd5af466',
    messagingSenderId: '765882164627',
    projectId: 'app-convention',
    authDomain: 'app-convention.firebaseapp.com',
    storageBucket: 'app-convention.firebasestorage.app',
    measurementId: 'G-LVQ1NCK0ND',
  );
}
